spring:
  cloud:
    gateway:
      routes:
        - id: r1
          uri: http://localhost:8080/
          predicates:
            - Path= /proprietaires/**
        - id: r2
          uri: http://localhost:8081/
          predicates:
            - Path= /infractions/**
        - id: r3
          uri: http://localhost:8080/
          predicates:
            - Path= /vehicules/**
